### ISSUE TITLE
Crash when using MLPD.SW_1d

### ISSUE THREAD

**Issue by Saladien** [btcorgtfo/ElliottWaveAnalyzer#6]
Hello,
i like your script. Unfortunately it keeps on crashing on me. Would love to know how to fix it :).
I attached the file that i used.
[MLPD.SW_1d_2013.csv](https://github.com/btcorgtfo/ElliottWaveAnalyzer/files/7503656/MLPD.SW_1d_2013.csv)
.
The Log:
D:\Users\aqawq\AppData\Local\Programs\Python\Python39\python.exe D:\Users\aqawq\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5457.59\plugins\python\helpers\pydev\pydevconsole.py --mode=client --port=57451
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['D:\\Users\\aqawq\\Documents\\WF Install Automizer', 'D:/Users/aqawq/Documents/WF Install Automizer'])
PyDev console: starting.
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
runfile('D:/Users/aqawq/Documents/WF Install Automizer/example_12345_impulsive_wave.py', wdir='D:/Users/aqawq/Documents/WF Install Automizer')
Start at idx: 1282
will run up to 0.579195M combinations.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w2_3: Wave2 is longer than 9x Wave1
Rule Violation of leading diagonal for condition w2_3: Wave2 is longer than 9x Wave1
Rule Violation of impulse for condition w2_3: Wave2 is longer than 9x Wave1
Rule Violation of leading diagonal for condition w2_3: Wave2 is longer than 9x Wave1
Rule Violation of impulse for condition w2_2: Wave2 is shorten than 20% of Wave1.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w2_3: Wave2 is longer than 9x Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_5: Wave3 more than 7 times longer than Wave1.
Rule Violation of leading diagonal for condition w3_5: Wave3 more than 7 times longer than Wave1.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of impulse for condition w5_1: End of Wave5 is lower than End of Wave3
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w2_2: Wave2 is shorten than 20% of Wave1.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w2_2: Wave2 is shorten than 20% of Wave1.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w2_3: Wave2 is longer than 9x Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_1: Wave3 is the shortest Wave.
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w3_2: End of Wave3 is lower than End of Wave1
Rule Violation of leading diagonal for condition w2_0: Trend lines of Wave1-3 and Wave2-4 not forming Leading Diagonal.
Rule Violation of impulse for condition w4_1: End of Wave4 is lower than End of Wave1
Rule Violation of leading diagonal for condition w4_2: Length of Wave4 is shorter than 1/3 of End of Wave1
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Users\aqawq\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5457.59\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Users\aqawq\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5457.59\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Users/aqawq/Documents/WF Install Automizer/example_12345_impulsive_wave.py", line 36, in <module>
    waves_up = wa.find_impulsive_wave(idx_start=idx_start, wave_config=new_option_impulse.values)
  File "D:\Users\aqawq\Documents\WF Install Automizer\models\WaveAnalyzer.py", line 108, in find_impulsive_wave
    if wave4.low > np.min(self.lows[wave4.low_idx:wave5.high_idx]):
  File "<__array_function__ internals>", line 5, in amin
  File "D:\Users\aqawq\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 2858, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "D:\Users\aqawq\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by btcorgtfo** [comment]
hi,

i've looked into your data. It looks sort of ugly, like there are a lot of data points where open, close, high, low are identical

additional, the data is in an overall downward trend. A downward trend with 12345 down, ABC correction up is not implemented yet.

The waverule for impulse downwards have to be different, e.g. high of wave 2 > low of wave 1 vs. in an upward trend you have the rule low of wave 2 lower than high of wave 1.

You can start testing with the find_monowave.py file an play around.

Delete all data before 2020-03-30 and try this code

```
df = pd.read_csv(r'data\btc-usd_1d.csv')
df = pd.read_csv(r'data\MLPD.SW_1d_2013.csv')
lows = np.array(list(df['Low']))
highs = np.array(list(df['High']))
dates = np.array(list(df['Date']))

# find a monowave down starting from the low at the 3rd index
mw_up = MonoWaveUp(lows=lows, highs=highs, dates=dates, idx_start=3, skip=2)
plot_monowave(df, mw_up)

# find a monowave down from the end of the monowave up
mw_down = MonoWaveDown(lows=lows, highs=highs, dates=dates, idx_start=mw_up.idx_end, skip=1)
plot_monowave(df, mw_down)
```

**Comment by shreesha-j** [comment]
hey did you get to know how to implement the corrective wave since there is the implementation of it in the main running file, 

I checked all your scripts so in the main file there is the only implementation of the impulse wave and u didn't apply the corrective function file from wave rules model

**Comment by eromoe** [comment]
https://github.com/btcorgtfo/ElliottWaveAnalyzer/blob/0fe516575d0e4e8f7dbafb3561dc320d36ad9ea6/models/WaveRules.py#L318

@btcorgtfo hi, why not return 0 when delta_x == 0 , it does happen in real world.
